<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\BishopW.png" />
    <None Remove="Assets\blackBishop.png" />
    <None Remove="Assets\blackKing.png" />
    <None Remove="Assets\blackKnight.png" />
    <None Remove="Assets\blackPawn.png" />
    <None Remove="Assets\blackQueen.png" />
    <None Remove="Assets\blackRook.png" />
    <None Remove="Assets\Board.png" />
    <None Remove="Assets\CursorB.cur" />
    <None Remove="Assets\CursorW.cur" />
    <None Remove="Assets\icon.ico" />
    <None Remove="Assets\KingB.png" />
    <None Remove="Assets\KingW.png" />
    <None Remove="Assets\KnightB.png" />
    <None Remove="Assets\KnightW.png" />
    <None Remove="Assets\PawnB.png" />
    <None Remove="Assets\PawnW.png" />
    <None Remove="Assets\QueenB.png" />
    <None Remove="Assets\QueenW.png" />
    <None Remove="Assets\RookB.png" />
    <None Remove="Assets\RookW.png" />
    <None Remove="Assets\whiteBishop.png" />
    <None Remove="Assets\whiteKing.png" />
    <None Remove="Assets\whiteKnight.png" />
    <None Remove="Assets\whitePawn.png" />
    <None Remove="Assets\whiteQueen.png" />
    <None Remove="Assets\whiteRook.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChessLogic\ChessLogic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\blackBishop.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\blackKing.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\blackKnight.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\blackPawn.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\blackQueen.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\blackRook.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Board.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\CursorB.cur" />
    <Resource Include="Assets\CursorW.cur" />
    <Resource Include="Assets\icon.ico" />
    <Resource Include="Assets\whiteBishop.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\whiteKing.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\whiteKnight.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\whitePawn.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\whiteQueen.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\whiteRook.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
